package com.zepto;

import android.view.View;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.RelativeLayout;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import com.nic.mparivahan.dlservices.data.model.DlAddress;
import com.nic.mparivahan.dlservices.widget.CustomWegetLayout;
import com.nic.mparivahan.dlservices.widget.MyTextView;

/* JADX INFO: loaded from: classes2.dex */
public abstract class a7 extends lq7 {
    public final EditText A;
    public final TextView A0;
    public final EditText B;
    public final TextView B0;
    public final EditText C;
    public final TextView C0;
    public final EditText D;
    public final TextView D0;
    public final EditText E;
    public final TextView E0;
    public final EditText F;
    public final MyTextView F0;
    public final EditText G;
    public final TextView G0;
    public final EditText H;
    public final TextView H0;
    public final RadioButton I;
    public final TextView I0;
    public final RadioButton J;
    public final TextView J0;
    public final RadioGroup K;
    public final TextView K0;
    public final EditText L;
    public final TextView L0;
    public final EditText M;
    public final TextView M0;
    public final EditText N;
    public final TextView N0;
    public final EditText O;
    public final MyTextView O0;
    public final EditText P;
    public final MyTextView P0;
    public final ImageView Q;
    public final TextView Q0;
    public final LinearLayout R;
    public final RadioButton R0;
    public final LinearLayout S;
    public final RadioGroup S0;
    public final ImageView T;
    public DlAddress T0;
    public final ImageView U;
    public DlAddress U0;
    public final RelativeLayout V;
    public final TextView W;
    public final CardView X;
    public final ImageView Y;
    public final LinearLayout Z;
    public final LinearLayout a0;
    public final LinearLayout b0;
    public final LinearLayout c0;
    public final vy3 d0;
    public final iy3 e0;
    public final RecyclerView f0;
    public final ImageView g0;
    public final ImageView h0;
    public final ImageView i0;
    public final ImageView j0;
    public final ProgressBar k0;
    public final MyTextView l0;
    public final MyTextView m0;
    public final bs4 n0;
    public final CardView o0;
    public final CheckBox p0;
    public final MyTextView q0;
    public final Spinner r0;
    public final CustomWegetLayout s0;
    public final RadioButton t0;
    public final TextView u0;
    public final TextView v0;
    public final EditText w;
    public final TextView w0;
    public final EditText x;
    public final MyTextView x0;
    public final EditText y;
    public final MyTextView y0;
    public final TextView z;
    public final TextView z0;

    public a7(Object obj, View view, int i, EditText editText, EditText editText2, EditText editText3, TextView textView, EditText editText4, EditText editText5, EditText editText6, EditText editText7, EditText editText8, EditText editText9, EditText editText10, EditText editText11, RadioButton radioButton, RadioButton radioButton2, RadioGroup radioGroup, EditText editText12, EditText editText13, EditText editText14, EditText editText15, EditText editText16, ImageView imageView, LinearLayout linearLayout, LinearLayout linearLayout2, ImageView imageView2, ImageView imageView3, RelativeLayout relativeLayout, TextView textView2, CardView cardView, ImageView imageView4, LinearLayout linearLayout3, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, vy3 vy3Var, iy3 iy3Var, RecyclerView recyclerView, ImageView imageView5, ImageView imageView6, ImageView imageView7, ImageView imageView8, ProgressBar progressBar, MyTextView myTextView, MyTextView myTextView2, bs4 bs4Var, CardView cardView2, CheckBox checkBox, MyTextView myTextView3, Spinner spinner, CustomWegetLayout customWegetLayout, RadioButton radioButton3, TextView textView3, TextView textView4, TextView textView5, MyTextView myTextView4, MyTextView myTextView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, MyTextView myTextView6, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, MyTextView myTextView7, MyTextView myTextView8, TextView textView20, RadioButton radioButton4, RadioGroup radioGroup2) {
        super(obj, view, i);
        this.w = editText;
        this.x = editText2;
        this.y = editText3;
        this.z = textView;
        this.A = editText4;
        this.B = editText5;
        this.C = editText6;
        this.D = editText7;
        this.E = editText8;
        this.F = editText9;
        this.G = editText10;
        this.H = editText11;
        this.I = radioButton;
        this.J = radioButton2;
        this.K = radioGroup;
        this.L = editText12;
        this.M = editText13;
        this.N = editText14;
        this.O = editText15;
        this.P = editText16;
        this.Q = imageView;
        this.R = linearLayout;
        this.S = linearLayout2;
        this.T = imageView2;
        this.U = imageView3;
        this.V = relativeLayout;
        this.W = textView2;
        this.X = cardView;
        this.Y = imageView4;
        this.Z = linearLayout3;
        this.a0 = linearLayout4;
        this.b0 = linearLayout5;
        this.c0 = linearLayout6;
        this.d0 = vy3Var;
        this.e0 = iy3Var;
        this.f0 = recyclerView;
        this.g0 = imageView5;
        this.h0 = imageView6;
        this.i0 = imageView7;
        this.j0 = imageView8;
        this.k0 = progressBar;
        this.l0 = myTextView;
        this.m0 = myTextView2;
        this.n0 = bs4Var;
        this.o0 = cardView2;
        this.p0 = checkBox;
        this.q0 = myTextView3;
        this.r0 = spinner;
        this.s0 = customWegetLayout;
        this.t0 = radioButton3;
        this.u0 = textView3;
        this.v0 = textView4;
        this.w0 = textView5;
        this.x0 = myTextView4;
        this.y0 = myTextView5;
        this.z0 = textView6;
        this.A0 = textView7;
        this.B0 = textView8;
        this.C0 = textView9;
        this.D0 = textView10;
        this.E0 = textView11;
        this.F0 = myTextView6;
        this.G0 = textView12;
        this.H0 = textView13;
        this.I0 = textView14;
        this.J0 = textView15;
        this.K0 = textView16;
        this.L0 = textView17;
        this.M0 = textView18;
        this.N0 = textView19;
        this.O0 = myTextView7;
        this.P0 = myTextView8;
        this.Q0 = textView20;
        this.R0 = radioButton4;
        this.S0 = radioGroup2;
    }

    public abstract void x(DlAddress dlAddress);

    public abstract void y(DlAddress dlAddress);
}
