package com.zepto;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.nic.mparivahan.MyTextView;
import com.nic.mparivahan.dlservices.data.model.ResultItemSubmit;

/* JADX INFO: loaded from: classes2.dex */
public abstract class a9 extends lq7 {
    public final TextView A;
    public final TextView B;
    public final TextView C;
    public final TextView D;
    public final TextView E;
    public final TextView F;
    public final ImageView G;
    public final MyTextView H;
    public final TextView I;
    public final ImageView J;
    public final ImageView K;
    public final TextView L;
    public final TextView M;
    public final TextView N;
    public final TextView O;
    public final TextView P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;
    public final TextView a0;
    public final vy3 b0;
    public final LinearLayout c0;
    public final LinearLayout d0;
    public final TextView e0;
    public final View f0;
    public final View g0;
    public final View h0;
    public final View i0;
    public final View j0;
    public final View k0;
    public ResultItemSubmit l0;
    public final TextView w;
    public final TextView x;
    public final TextView y;
    public final TextView z;

    public a9(Object obj, View view, int i, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, ImageView imageView, MyTextView myTextView, TextView textView11, ImageView imageView2, ImageView imageView3, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, vy3 vy3Var, LinearLayout linearLayout, LinearLayout linearLayout2, TextView textView28, View view2, View view3, View view4, View view5, View view6, View view7) {
        super(obj, view, i);
        this.w = textView;
        this.x = textView2;
        this.y = textView3;
        this.z = textView4;
        this.A = textView5;
        this.B = textView6;
        this.C = textView7;
        this.D = textView8;
        this.E = textView9;
        this.F = textView10;
        this.G = imageView;
        this.H = myTextView;
        this.I = textView11;
        this.J = imageView2;
        this.K = imageView3;
        this.L = textView12;
        this.M = textView13;
        this.N = textView14;
        this.O = textView15;
        this.P = textView16;
        this.Q = textView17;
        this.R = textView18;
        this.S = textView19;
        this.T = textView20;
        this.U = textView21;
        this.V = textView22;
        this.W = textView23;
        this.X = textView24;
        this.Y = textView25;
        this.Z = textView26;
        this.a0 = textView27;
        this.b0 = vy3Var;
        this.c0 = linearLayout;
        this.d0 = linearLayout2;
        this.e0 = textView28;
        this.f0 = view2;
        this.g0 = view3;
        this.h0 = view4;
        this.i0 = view5;
        this.j0 = view6;
        this.k0 = view7;
    }
}
