package com.zepto;

import android.view.View;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatEditText;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import com.nic.mparivahan.dlservices.widget.CustomWegetLayout;
import com.nic.mparivahan.dlservices.widget.MyTextView;

/* JADX INFO: loaded from: classes2.dex */
public abstract class cc extends lq7 {
    public final CardView A;
    public final MyTextView A0;
    public final AppCompatEditText B;
    public final MyTextView B0;
    public final EditText C;
    public final MyTextView C0;
    public final AppCompatEditText D;
    public final MyTextView D0;
    public final EditText E;
    public final MyTextView E0;
    public final EditText F;
    public final MyTextView F0;
    public final TextView G;
    public final MyTextView G0;
    public final EditText H;
    public final MyTextView H0;
    public final EditText I;
    public final MyTextView I0;
    public final EditText J;
    public final MyTextView J0;
    public final EditText K;
    public final MyTextView K0;
    public final EditText L;
    public final TextView L0;
    public final EditText M;
    public final EditText M0;
    public final EditText N;
    public final EditText N0;
    public final EditText O;
    public Boolean O0;
    public final EditText P;
    public final EditText Q;
    public final EditText R;
    public final TextView S;
    public final CustomWegetLayout T;
    public final EditText U;
    public final MyTextView V;
    public final RadioButton W;
    public final RadioButton X;
    public final RadioButton Y;
    public final RadioGroup Z;
    public final RadioGroup a0;
    public final RadioButton b0;
    public final ImageView c0;
    public final vy3 d0;
    public final iy3 e0;
    public final RecyclerView f0;
    public final EditText g0;
    public final EditText h0;
    public final ex2 i0;
    public final CustomWegetLayout j0;
    public final CardView k0;
    public final MyTextView l0;
    public final Spinner m0;
    public final MyTextView n0;
    public final MyTextView o0;
    public final MyTextView p0;
    public final MyTextView q0;
    public final MyTextView r0;
    public final AppCompatTextView s0;
    public final MyTextView t0;
    public final MyTextView u0;
    public final MyTextView v0;
    public final TextView w;
    public final MyTextView w0;
    public final CheckBox x;
    public final MyTextView x0;
    public final LinearLayout y;
    public final MyTextView y0;
    public final LinearLayout z;
    public final MyTextView z0;

    public cc(Object obj, View view, int i, TextView textView, CheckBox checkBox, LinearLayout linearLayout, LinearLayout linearLayout2, CardView cardView, AppCompatEditText appCompatEditText, EditText editText, AppCompatEditText appCompatEditText2, EditText editText2, EditText editText3, TextView textView2, EditText editText4, EditText editText5, EditText editText6, EditText editText7, EditText editText8, EditText editText9, EditText editText10, EditText editText11, EditText editText12, EditText editText13, EditText editText14, TextView textView3, CustomWegetLayout customWegetLayout, EditText editText15, MyTextView myTextView, RadioButton radioButton, RadioButton radioButton2, RadioButton radioButton3, RadioGroup radioGroup, RadioGroup radioGroup2, RadioButton radioButton4, ImageView imageView, vy3 vy3Var, iy3 iy3Var, RecyclerView recyclerView, EditText editText16, EditText editText17, ex2 ex2Var, CustomWegetLayout customWegetLayout2, CardView cardView2, MyTextView myTextView2, Spinner spinner, MyTextView myTextView3, MyTextView myTextView4, MyTextView myTextView5, MyTextView myTextView6, MyTextView myTextView7, AppCompatTextView appCompatTextView, MyTextView myTextView8, MyTextView myTextView9, MyTextView myTextView10, MyTextView myTextView11, MyTextView myTextView12, MyTextView myTextView13, MyTextView myTextView14, MyTextView myTextView15, MyTextView myTextView16, MyTextView myTextView17, MyTextView myTextView18, MyTextView myTextView19, MyTextView myTextView20, MyTextView myTextView21, MyTextView myTextView22, MyTextView myTextView23, MyTextView myTextView24, MyTextView myTextView25, TextView textView4, EditText editText18, EditText editText19) {
        super(obj, view, i);
        this.w = textView;
        this.x = checkBox;
        this.y = linearLayout;
        this.z = linearLayout2;
        this.A = cardView;
        this.B = appCompatEditText;
        this.C = editText;
        this.D = appCompatEditText2;
        this.E = editText2;
        this.F = editText3;
        this.G = textView2;
        this.H = editText4;
        this.I = editText5;
        this.J = editText6;
        this.K = editText7;
        this.L = editText8;
        this.M = editText9;
        this.N = editText10;
        this.O = editText11;
        this.P = editText12;
        this.Q = editText13;
        this.R = editText14;
        this.S = textView3;
        this.T = customWegetLayout;
        this.U = editText15;
        this.V = myTextView;
        this.W = radioButton;
        this.X = radioButton2;
        this.Y = radioButton3;
        this.Z = radioGroup;
        this.a0 = radioGroup2;
        this.b0 = radioButton4;
        this.c0 = imageView;
        this.d0 = vy3Var;
        this.e0 = iy3Var;
        this.f0 = recyclerView;
        this.g0 = editText16;
        this.h0 = editText17;
        this.i0 = ex2Var;
        this.j0 = customWegetLayout2;
        this.k0 = cardView2;
        this.l0 = myTextView2;
        this.m0 = spinner;
        this.n0 = myTextView3;
        this.o0 = myTextView4;
        this.p0 = myTextView5;
        this.q0 = myTextView6;
        this.r0 = myTextView7;
        this.s0 = appCompatTextView;
        this.t0 = myTextView8;
        this.u0 = myTextView9;
        this.v0 = myTextView10;
        this.w0 = myTextView11;
        this.x0 = myTextView12;
        this.y0 = myTextView13;
        this.z0 = myTextView14;
        this.A0 = myTextView15;
        this.B0 = myTextView16;
        this.C0 = myTextView17;
        this.D0 = myTextView18;
        this.E0 = myTextView19;
        this.F0 = myTextView20;
        this.G0 = myTextView21;
        this.H0 = myTextView22;
        this.I0 = myTextView23;
        this.J0 = myTextView24;
        this.K0 = myTextView25;
        this.L0 = textView4;
        this.M0 = editText18;
        this.N0 = editText19;
    }

    public abstract void x(Boolean bool);
}
