package com.zepto;

import com.nic.mparivahan.VahanServices.VahanConst.VContant;

/* JADX INFO: loaded from: classes3.dex */
public interface hk4 {
    public static final p0 A;
    public static final p0 B;
    public static final p0 C;
    public static final p0 D;
    public static final p0 E;
    public static final p0 F;
    public static final p0 G;
    public static final p0 H;
    public static final p0 I;
    public static final p0 J;
    public static final p0 K;
    public static final p0 L;
    public static final p0 M;
    public static final p0 N;
    public static final p0 O;
    public static final p0 P;
    public static final p0 Q;
    public static final p0 R;
    public static final p0 S;
    public static final p0 T;
    public static final p0 U;
    public static final p0 V;
    public static final p0 W;
    public static final p0 X;
    public static final p0 Y;
    public static final p0 a;
    public static final p0 b;
    public static final p0 c;
    public static final p0 d;
    public static final p0 e;
    public static final p0 f;
    public static final p0 g;
    public static final p0 h;
    public static final p0 i;
    public static final p0 j;
    public static final p0 k;
    public static final p0 l;
    public static final p0 m;
    public static final p0 n;
    public static final p0 o;
    public static final p0 p;
    public static final p0 q;
    public static final p0 r;
    public static final p0 s;
    public static final p0 t;
    public static final p0 u;
    public static final p0 v;
    public static final p0 w;
    public static final p0 x;
    public static final p0 y;
    public static final p0 z;

    static {
        p0 p0Var = new p0("1.3.6.1.4.1.8301.3.1.3.5.3.2");
        a = p0Var;
        b = p0Var.g0(VContant.MAINSCREEN);
        c = p0Var.g0(VContant.APPLICATION_SCREEN);
        d = p0Var.g0("3");
        e = p0Var.g0("4");
        f = p0Var.g0(VContant.TRANFER_OF_OWNERSHIP_PURPOSE_CODE);
        p0 p0Var2 = new p0("1.3.6.1.4.1.8301.3.1.3.3");
        g = p0Var2;
        h = p0Var2.g0(VContant.MAINSCREEN);
        i = p0Var2.g0(VContant.APPLICATION_SCREEN);
        j = p0Var2.g0("3");
        k = p0Var2.g0("4");
        l = p0Var2.g0(VContant.TRANFER_OF_OWNERSHIP_PURPOSE_CODE);
        m = new p0("1.3.6.1.4.1.8301.3.1.3.4.1");
        n = new p0("1.3.6.1.4.1.8301.3.1.3.4.2");
        o = new p0("1.3.6.1.4.1.8301.3.1.3.4.2.1");
        p = new p0("1.3.6.1.4.1.8301.3.1.3.4.2.2");
        q = new p0("1.3.6.1.4.1.8301.3.1.3.4.2.3");
        r = m20.s;
        s = m20.t;
        t = m20.u;
        u = m20.v;
        v = m20.f0;
        w = m20.w;
        p0 p0Var3 = m20.x;
        x = p0Var3;
        p0 p0Var4 = m20.y;
        y = p0Var4;
        p0 p0Var5 = m20.z;
        z = p0Var5;
        p0 p0Var6 = m20.A;
        A = p0Var6;
        B = m20.B;
        C = m20.C;
        D = m20.D;
        E = m20.E;
        F = m20.F;
        p0 p0Var7 = m20.G;
        G = p0Var7;
        p0 p0Var8 = m20.H;
        H = p0Var8;
        I = m20.I;
        J = m20.J;
        K = m20.K;
        L = m20.L;
        p0 p0Var9 = m20.M;
        M = p0Var9;
        p0 p0Var10 = m20.N;
        N = p0Var10;
        O = p0Var3;
        P = p0Var4;
        Q = p0Var5;
        R = p0Var6;
        S = p0Var7;
        T = p0Var8;
        U = p0Var9;
        V = p0Var10;
        W = m20.W;
        X = m20.c0;
        Y = m20.d0;
    }
}
