package com.zepto;

import com.nic.mparivahan.VahanServices.VahanConst.VContant;

/* JADX INFO: loaded from: classes3.dex */
public interface l14 {
    public static final p0 A;
    public static final p0 B;
    public static final p0 C;
    public static final p0 D;
    public static final p0 E;
    public static final p0 F;
    public static final p0 G;
    public static final p0 H;
    public static final p0 I;
    public static final p0 J;
    public static final p0 K;
    public static final p0 L;
    public static final p0 M;
    public static final p0 N;
    public static final p0 O;
    public static final p0 P;
    public static final p0 Q;
    public static final p0 R;
    public static final p0 S;
    public static final p0 T;
    public static final p0 U;
    public static final p0 V;
    public static final p0 W;
    public static final p0 X;
    public static final p0 Y;
    public static final p0 Z;
    public static final p0 a;
    public static final p0 a0;
    public static final p0 b;
    public static final p0 b0;
    public static final p0 c;
    public static final p0 c0;
    public static final p0 d;
    public static final p0 d0;
    public static final p0 e;
    public static final p0 e0;
    public static final p0 f;
    public static final p0 f0;
    public static final p0 g;
    public static final p0 g0;
    public static final p0 h;
    public static final p0 h0;
    public static final p0 i;
    public static final p0 i0;
    public static final p0 j;
    public static final p0 j0;
    public static final p0 k;
    public static final p0 k0;
    public static final p0 l;
    public static final p0 l0;
    public static final p0 m;
    public static final p0 m0;
    public static final p0 n;
    public static final p0 o;
    public static final p0 p;
    public static final p0 q;
    public static final p0 r;
    public static final p0 s;
    public static final p0 t;
    public static final p0 u;
    public static final p0 v;
    public static final p0 w;
    public static final p0 x;
    public static final p0 y;
    public static final p0 z;

    static {
        p0 p0Var = new p0("2.16.840.1.101.3.4");
        a = p0Var;
        p0 p0VarG0 = p0Var.g0(VContant.APPLICATION_SCREEN);
        b = p0VarG0;
        c = p0VarG0.g0(VContant.MAINSCREEN);
        d = p0VarG0.g0(VContant.APPLICATION_SCREEN);
        e = p0VarG0.g0("3");
        f = p0VarG0.g0("4");
        g = p0VarG0.g0(VContant.TRANFER_OF_OWNERSHIP_PURPOSE_CODE);
        h = p0VarG0.g0(VContant.HYPOTHECATION_ADDITION_PURPOSE_CODE);
        i = p0VarG0.g0(VContant.HYPOTHICATION_TERMINATION_PURPOSE_CODE);
        j = p0VarG0.g0(VContant.HYPOTHECATION_CONTINUATION_PURPOSE_CODE);
        k = p0VarG0.g0(VContant.NOC_PURPOSE_CODE);
        l = p0VarG0.g0("10");
        m = p0VarG0.g0("11");
        n = p0VarG0.g0("12");
        o = p0VarG0.g0(VContant.RCPARTICULAR_PURPOSE_CODE);
        p = p0VarG0.g0(VContant.DUPLICATE_FITNESS_PURPOSE_CODE);
        q = p0VarG0.g0("15");
        r = p0VarG0.g0(VContant.ALTERATION_PURPOSE_CODE);
        s = p0VarG0.g0("17");
        t = p0VarG0.g0("18");
        u = p0VarG0.g0("19");
        v = p0VarG0.g0("20");
        p0 p0VarG02 = p0Var.g0(VContant.MAINSCREEN);
        w = p0VarG02;
        x = p0VarG02.g0(VContant.MAINSCREEN);
        y = p0VarG02.g0(VContant.APPLICATION_SCREEN);
        z = p0VarG02.g0("3");
        A = p0VarG02.g0("4");
        B = p0VarG02.g0(VContant.TRANFER_OF_OWNERSHIP_PURPOSE_CODE);
        C = p0VarG02.g0(VContant.HYPOTHECATION_ADDITION_PURPOSE_CODE);
        D = p0VarG02.g0(VContant.HYPOTHICATION_TERMINATION_PURPOSE_CODE);
        E = p0VarG02.g0(VContant.HYPOTHECATION_CONTINUATION_PURPOSE_CODE);
        F = p0VarG02.g0("21");
        G = p0VarG02.g0("22");
        H = p0VarG02.g0("23");
        I = p0VarG02.g0("24");
        J = p0VarG02.g0("25");
        K = p0VarG02.g0("26");
        L = p0VarG02.g0(VContant.RC_PERMIT_RENEWAL_PURPOSE_CODE);
        M = p0VarG02.g0(VContant.PERMIT_TRANSFER_PURPOSE_CODE);
        N = p0VarG02.g0("41");
        O = p0VarG02.g0("42");
        P = p0VarG02.g0("43");
        Q = p0VarG02.g0("44");
        R = p0VarG02.g0("45");
        S = p0VarG02.g0("46");
        T = p0VarG02.g0("47");
        U = p0VarG02.g0(VContant.MISELL_PURPOSE_CODE);
        p0 p0VarG03 = p0Var.g0("3");
        V = p0VarG03;
        W = p0VarG03;
        X = p0VarG03.g0(VContant.MAINSCREEN);
        Y = p0VarG03.g0(VContant.APPLICATION_SCREEN);
        Z = p0VarG03.g0("3");
        a0 = p0VarG03.g0("4");
        b0 = p0VarG03.g0(VContant.TRANFER_OF_OWNERSHIP_PURPOSE_CODE);
        c0 = p0VarG03.g0(VContant.HYPOTHECATION_ADDITION_PURPOSE_CODE);
        d0 = p0VarG03.g0(VContant.HYPOTHICATION_TERMINATION_PURPOSE_CODE);
        e0 = p0VarG03.g0(VContant.HYPOTHECATION_CONTINUATION_PURPOSE_CODE);
        f0 = p0VarG03.g0(VContant.NOC_PURPOSE_CODE);
        g0 = p0VarG03.g0("10");
        h0 = p0VarG03.g0("11");
        i0 = p0VarG03.g0("12");
        j0 = p0VarG03.g0(VContant.RCPARTICULAR_PURPOSE_CODE);
        k0 = p0VarG03.g0(VContant.DUPLICATE_FITNESS_PURPOSE_CODE);
        l0 = p0VarG03.g0("15");
        m0 = p0VarG03.g0(VContant.ALTERATION_PURPOSE_CODE);
    }
}
