package com.zepto;

import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;
import kotlin.UByte;

/* JADX INFO: loaded from: classes.dex */
public class lp4 extends rp4 implements Comparable {
    public static Map Gb;
    public int f;
    public static final lp4 g = new lp4("3D");
    public static final lp4 h = new lp4("A");
    public static final lp4 i = new lp4("A85");
    public static final lp4 j = new lp4("AA");
    public static final lp4 k = new lp4("AbsoluteColorimetric");
    public static final lp4 l = new lp4("AC");
    public static final lp4 m = new lp4("AcroForm");
    public static final lp4 n = new lp4("Action");
    public static final lp4 o = new lp4("Activation");
    public static final lp4 p = new lp4("ADBE");
    public static final lp4 q = new lp4("ActualText");
    public static final lp4 r = new lp4("adbe.pkcs7.detached");
    public static final lp4 s = new lp4("adbe.pkcs7.s4");
    public static final lp4 t = new lp4("adbe.pkcs7.s5");
    public static final lp4 u = new lp4("adbe.pkcs7.sha1");
    public static final lp4 v = new lp4("adbe.x509.rsa_sha1");
    public static final lp4 w = new lp4("Adobe.PPKLite");
    public static final lp4 x = new lp4("Adobe.PPKMS");
    public static final lp4 y = new lp4("AESV2");
    public static final lp4 z = new lp4("AHx");
    public static final lp4 A = new lp4("AIS");
    public static final lp4 B = new lp4("AllPages");
    public static final lp4 C = new lp4("Alt");
    public static final lp4 D = new lp4("Alternate");
    public static final lp4 E = new lp4("And");
    public static final lp4 F = new lp4("Animation");
    public static final lp4 G = new lp4("Annot");
    public static final lp4 H = new lp4("Annots");
    public static final lp4 I = new lp4("AntiAlias");
    public static final lp4 J = new lp4("AP");
    public static final lp4 K = new lp4("AppDefault");
    public static final lp4 L = new lp4("Art");
    public static final lp4 M = new lp4("ArtBox");
    public static final lp4 N = new lp4("Ascent");
    public static final lp4 O = new lp4("AS");
    public static final lp4 P = new lp4("ASCII85Decode");
    public static final lp4 Q = new lp4("ASCIIHexDecode");
    public static final lp4 R = new lp4("Asset");
    public static final lp4 S = new lp4("Assets");
    public static final lp4 T = new lp4("AuthEvent");
    public static final lp4 U = new lp4("Author");
    public static final lp4 V = new lp4("B");
    public static final lp4 W = new lp4("Background");
    public static final lp4 X = new lp4("BaseEncoding");
    public static final lp4 Y = new lp4("BaseFont");
    public static final lp4 Z = new lp4("BaseVersion");
    public static final lp4 a0 = new lp4("BBox");
    public static final lp4 b0 = new lp4("BC");
    public static final lp4 c0 = new lp4("BG");
    public static final lp4 d0 = new lp4("BibEntry");
    public static final lp4 e0 = new lp4("BigFive");
    public static final lp4 f0 = new lp4("Binding");
    public static final lp4 g0 = new lp4("BindingMaterialName");
    public static final lp4 h0 = new lp4("BitsPerComponent");
    public static final lp4 i0 = new lp4("BitsPerSample");
    public static final lp4 j0 = new lp4("Bl");
    public static final lp4 k0 = new lp4("BlackIs1");
    public static final lp4 l0 = new lp4("BlackPoint");
    public static final lp4 m0 = new lp4("BlockQuote");
    public static final lp4 n0 = new lp4("BleedBox");
    public static final lp4 o0 = new lp4("Blinds");
    public static final lp4 p0 = new lp4("BM");
    public static final lp4 q0 = new lp4("Border");
    public static final lp4 r0 = new lp4("Bounds");
    public static final lp4 s0 = new lp4("Box");
    public static final lp4 t0 = new lp4("BS");
    public static final lp4 u0 = new lp4("Btn");
    public static final lp4 v0 = new lp4("ByteRange");
    public static final lp4 w0 = new lp4("C");
    public static final lp4 x0 = new lp4("C0");
    public static final lp4 y0 = new lp4("C1");
    public static final lp4 z0 = new lp4("CA");
    public static final lp4 A0 = new lp4("ca");
    public static final lp4 B0 = new lp4("CalGray");
    public static final lp4 C0 = new lp4("CalRGB");
    public static final lp4 D0 = new lp4("CapHeight");
    public static final lp4 E0 = new lp4("Caption");
    public static final lp4 F0 = new lp4("Catalog");
    public static final lp4 G0 = new lp4("Category");
    public static final lp4 H0 = new lp4("CCITTFaxDecode");
    public static final lp4 I0 = new lp4("Center");
    public static final lp4 J0 = new lp4("CenterWindow");
    public static final lp4 K0 = new lp4("Cert");
    public static final lp4 L0 = new lp4("CF");
    public static final lp4 M0 = new lp4("CFM");
    public static final lp4 N0 = new lp4("Ch");
    public static final lp4 O0 = new lp4("CharProcs");
    public static final lp4 P0 = new lp4("CheckSum");
    public static final lp4 Q0 = new lp4("CI");
    public static final lp4 R0 = new lp4("CIDFontType0");
    public static final lp4 S0 = new lp4("CIDFontType2");
    public static final lp4 T0 = new lp4("CIDSet");
    public static final lp4 U0 = new lp4("CIDSystemInfo");
    public static final lp4 V0 = new lp4("CIDToGIDMap");
    public static final lp4 W0 = new lp4("Circle");
    public static final lp4 X0 = new lp4("CMD");
    public static final lp4 Y0 = new lp4("CO");
    public static final lp4 Z0 = new lp4("Code");
    public static final lp4 a1 = new lp4("Colors");
    public static final lp4 b1 = new lp4("ColorSpace");
    public static final lp4 c1 = new lp4("Collection");
    public static final lp4 d1 = new lp4("CollectionField");
    public static final lp4 e1 = new lp4("CollectionItem");
    public static final lp4 f1 = new lp4("CollectionSchema");
    public static final lp4 g1 = new lp4("CollectionSort");
    public static final lp4 h1 = new lp4("CollectionSubitem");
    public static final lp4 i1 = new lp4("Columns");
    public static final lp4 j1 = new lp4("Condition");
    public static final lp4 k1 = new lp4("Configuration");
    public static final lp4 l1 = new lp4("Configurations");
    public static final lp4 m1 = new lp4("ContactInfo");
    public static final lp4 n1 = new lp4("Content");
    public static final lp4 o1 = new lp4("Contents");
    public static final lp4 p1 = new lp4("Coords");
    public static final lp4 q1 = new lp4("Count");
    public static final lp4 r1 = new lp4("Courier");
    public static final lp4 s1 = new lp4("Courier-Bold");
    public static final lp4 t1 = new lp4("Courier-Oblique");
    public static final lp4 u1 = new lp4("Courier-BoldOblique");
    public static final lp4 v1 = new lp4("CreationDate");
    public static final lp4 w1 = new lp4("Creator");
    public static final lp4 x1 = new lp4("CreatorInfo");
    public static final lp4 y1 = new lp4("CropBox");
    public static final lp4 z1 = new lp4("Crypt");
    public static final lp4 A1 = new lp4("CS");
    public static final lp4 B1 = new lp4("CuePoint");
    public static final lp4 C1 = new lp4("CuePoints");
    public static final lp4 D1 = new lp4("D");
    public static final lp4 E1 = new lp4("DA");
    public static final lp4 F1 = new lp4("Data");
    public static final lp4 G1 = new lp4("DC");
    public static final lp4 H1 = new lp4("DCTDecode");
    public static final lp4 I1 = new lp4("Deactivation");
    public static final lp4 J1 = new lp4("Decode");
    public static final lp4 K1 = new lp4("DecodeParms");
    public static final lp4 L1 = new lp4("Default");
    public static final lp4 M1 = new lp4("DefaultCryptFilter");
    public static final lp4 N1 = new lp4("DefaultCMYK");
    public static final lp4 O1 = new lp4("DefaultGray");
    public static final lp4 P1 = new lp4("DefaultRGB");
    public static final lp4 Q1 = new lp4("Desc");
    public static final lp4 R1 = new lp4("DescendantFonts");
    public static final lp4 S1 = new lp4("Descent");
    public static final lp4 T1 = new lp4("Dest");
    public static final lp4 U1 = new lp4("DestOutputProfile");
    public static final lp4 V1 = new lp4("Dests");
    public static final lp4 W1 = new lp4("DeviceGray");
    public static final lp4 X1 = new lp4("DeviceRGB");
    public static final lp4 Y1 = new lp4("DeviceCMYK");
    public static final lp4 Z1 = new lp4("Di");
    public static final lp4 a2 = new lp4("Differences");
    public static final lp4 b2 = new lp4("Dissolve");
    public static final lp4 c2 = new lp4("Direction");
    public static final lp4 d2 = new lp4("DisplayDocTitle");
    public static final lp4 e2 = new lp4("Div");
    public static final lp4 f2 = new lp4("DL");
    public static final lp4 g2 = new lp4("Dm");
    public static final lp4 h2 = new lp4("DocMDP");
    public static final lp4 i2 = new lp4("DocOpen");
    public static final lp4 j2 = new lp4("Document");
    public static final lp4 k2 = new lp4("Domain");
    public static final lp4 l2 = new lp4("DP");
    public static final lp4 m2 = new lp4("DR");
    public static final lp4 n2 = new lp4("DS");
    public static final lp4 o2 = new lp4("Dur");
    public static final lp4 p2 = new lp4("Duplex");
    public static final lp4 q2 = new lp4("DuplexFlipShortEdge");
    public static final lp4 r2 = new lp4("DuplexFlipLongEdge");
    public static final lp4 s2 = new lp4("DV");
    public static final lp4 t2 = new lp4("DW");
    public static final lp4 u2 = new lp4("E");
    public static final lp4 v2 = new lp4("EarlyChange");
    public static final lp4 w2 = new lp4("EF");
    public static final lp4 x2 = new lp4("EFF");
    public static final lp4 y2 = new lp4("EFOpen");
    public static final lp4 z2 = new lp4("Embedded");
    public static final lp4 A2 = new lp4("EmbeddedFile");
    public static final lp4 B2 = new lp4("EmbeddedFiles");
    public static final lp4 C2 = new lp4("Encode");
    public static final lp4 D2 = new lp4("EncodedByteAlign");
    public static final lp4 E2 = new lp4("Encoding");
    public static final lp4 F2 = new lp4("Encrypt");
    public static final lp4 G2 = new lp4("EncryptMetadata");
    public static final lp4 H2 = new lp4("EndOfBlock");
    public static final lp4 I2 = new lp4("EndOfLine");
    public static final lp4 J2 = new lp4("Extend");
    public static final lp4 K2 = new lp4("Extensions");
    public static final lp4 L2 = new lp4("ExtensionLevel");
    public static final lp4 M2 = new lp4("ExtGState");
    public static final lp4 N2 = new lp4("Export");
    public static final lp4 O2 = new lp4("ExportState");
    public static final lp4 P2 = new lp4("Event");
    public static final lp4 Q2 = new lp4("F");
    public static final lp4 R2 = new lp4("Far");
    public static final lp4 S2 = new lp4("FB");
    public static final lp4 T2 = new lp4("FDecodeParms");
    public static final lp4 U2 = new lp4("FDF");
    public static final lp4 V2 = new lp4("Ff");
    public static final lp4 W2 = new lp4("FFilter");
    public static final lp4 X2 = new lp4("FG");
    public static final lp4 Y2 = new lp4("Fields");
    public static final lp4 Z2 = new lp4("Figure");
    public static final lp4 a3 = new lp4("FileAttachment");
    public static final lp4 b3 = new lp4("Filespec");
    public static final lp4 c3 = new lp4("Filter");
    public static final lp4 d3 = new lp4("First");
    public static final lp4 e3 = new lp4("FirstChar");
    public static final lp4 f3 = new lp4("FirstPage");
    public static final lp4 g3 = new lp4("Fit");
    public static final lp4 h3 = new lp4("FitH");
    public static final lp4 i3 = new lp4("FitV");
    public static final lp4 j3 = new lp4("FitR");
    public static final lp4 k3 = new lp4("FitB");
    public static final lp4 l3 = new lp4("FitBH");
    public static final lp4 m3 = new lp4("FitBV");
    public static final lp4 n3 = new lp4("FitWindow");
    public static final lp4 o3 = new lp4("Fl");
    public static final lp4 p3 = new lp4("Flags");
    public static final lp4 q3 = new lp4("Flash");
    public static final lp4 r3 = new lp4("FlashVars");
    public static final lp4 s3 = new lp4("FlateDecode");
    public static final lp4 t3 = new lp4("Fo");
    public static final lp4 u3 = new lp4("Font");
    public static final lp4 v3 = new lp4("FontBBox");
    public static final lp4 w3 = new lp4("FontDescriptor");
    public static final lp4 x3 = new lp4("FontFile");
    public static final lp4 y3 = new lp4("FontFile2");
    public static final lp4 z3 = new lp4("FontFile3");
    public static final lp4 A3 = new lp4("FontMatrix");
    public static final lp4 B3 = new lp4("FontName");
    public static final lp4 C3 = new lp4("Foreground");
    public static final lp4 D3 = new lp4("Form");
    public static final lp4 E3 = new lp4("FormType");
    public static final lp4 F3 = new lp4("Formula");
    public static final lp4 G3 = new lp4("FreeText");
    public static final lp4 H3 = new lp4("FRM");
    public static final lp4 I3 = new lp4("FS");
    public static final lp4 J3 = new lp4("FT");
    public static final lp4 K3 = new lp4("FullScreen");
    public static final lp4 L3 = new lp4("Function");
    public static final lp4 M3 = new lp4("Functions");
    public static final lp4 N3 = new lp4("FunctionType");
    public static final lp4 O3 = new lp4("Gamma");
    public static final lp4 P3 = new lp4("GBK");
    public static final lp4 Q3 = new lp4("Glitter");
    public static final lp4 R3 = new lp4("GoTo");
    public static final lp4 S3 = new lp4("GoToE");
    public static final lp4 T3 = new lp4("GoToR");
    public static final lp4 U3 = new lp4("Group");
    public static final lp4 V3 = new lp4("GTS_PDFA1");
    public static final lp4 W3 = new lp4("GTS_PDFX");
    public static final lp4 X3 = new lp4("GTS_PDFXVersion");
    public static final lp4 Y3 = new lp4("H");
    public static final lp4 Z3 = new lp4("H1");
    public static final lp4 a4 = new lp4("H2");
    public static final lp4 b4 = new lp4("H3");
    public static final lp4 c4 = new lp4("H4");
    public static final lp4 d4 = new lp4("H5");
    public static final lp4 e4 = new lp4("H6");
    public static final lp4 f4 = new lp4("HAlign");
    public static final lp4 g4 = new lp4("Height");
    public static final lp4 h4 = new lp4("Helv");
    public static final lp4 i4 = new lp4("Helvetica");
    public static final lp4 j4 = new lp4("Helvetica-Bold");
    public static final lp4 k4 = new lp4("Helvetica-Oblique");
    public static final lp4 l4 = new lp4("Helvetica-BoldOblique");
    public static final lp4 m4 = new lp4("HF");
    public static final lp4 n4 = new lp4("Hid");
    public static final lp4 o4 = new lp4("Hide");
    public static final lp4 p4 = new lp4("HideMenubar");
    public static final lp4 q4 = new lp4("HideToolbar");
    public static final lp4 r4 = new lp4("HideWindowUI");
    public static final lp4 s4 = new lp4("Highlight");
    public static final lp4 t4 = new lp4("HOffset");
    public static final lp4 u4 = new lp4("I");
    public static final lp4 v4 = new lp4("ICCBased");
    public static final lp4 w4 = new lp4("ID");
    public static final lp4 x4 = new lp4("Identity");
    public static final lp4 y4 = new lp4("IF");
    public static final lp4 z4 = new lp4("Image");
    public static final lp4 A4 = new lp4("ImageB");
    public static final lp4 B4 = new lp4("ImageC");
    public static final lp4 C4 = new lp4("ImageI");
    public static final lp4 D4 = new lp4("ImageMask");
    public static final lp4 E4 = new lp4("Ind");
    public static final lp4 F4 = new lp4("Index");
    public static final lp4 G4 = new lp4("Indexed");
    public static final lp4 H4 = new lp4("Info");
    public static final lp4 I4 = new lp4("Ink");
    public static final lp4 J4 = new lp4("InkList");
    public static final lp4 K4 = new lp4("Instances");
    public static final lp4 L4 = new lp4("ImportData");
    public static final lp4 M4 = new lp4("Intent");
    public static final lp4 N4 = new lp4("Interpolate");
    public static final lp4 O4 = new lp4("IsMap");
    public static final lp4 P4 = new lp4("IRT");
    public static final lp4 Q4 = new lp4("ItalicAngle");
    public static final lp4 R4 = new lp4("ITXT");
    public static final lp4 S4 = new lp4("IX");
    public static final lp4 T4 = new lp4("JavaScript");
    public static final lp4 U4 = new lp4("JBIG2Decode");
    public static final lp4 V4 = new lp4("JBIG2Globals");
    public static final lp4 W4 = new lp4("JPXDecode");
    public static final lp4 X4 = new lp4("JS");
    public static final lp4 Y4 = new lp4("K");
    public static final lp4 Z4 = new lp4("Keywords");
    public static final lp4 a5 = new lp4("Kids");
    public static final lp4 b5 = new lp4("L");
    public static final lp4 c5 = new lp4("L2R");
    public static final lp4 d5 = new lp4("Lang");
    public static final lp4 e5 = new lp4("Language");
    public static final lp4 f5 = new lp4("Last");
    public static final lp4 g5 = new lp4("LastChar");
    public static final lp4 h5 = new lp4("LastPage");
    public static final lp4 i5 = new lp4("Launch");
    public static final lp4 j5 = new lp4("Lbl");
    public static final lp4 k5 = new lp4("LBody");
    public static final lp4 l5 = new lp4("Length");
    public static final lp4 m5 = new lp4("Length1");
    public static final lp4 n5 = new lp4("LI");
    public static final lp4 o5 = new lp4("Limits");
    public static final lp4 p5 = new lp4("Line");
    public static final lp4 q5 = new lp4("Linear");
    public static final lp4 r5 = new lp4("Link");
    public static final lp4 s5 = new lp4("ListMode");
    public static final lp4 t5 = new lp4("Location");
    public static final lp4 u5 = new lp4("Lock");
    public static final lp4 v5 = new lp4("Locked");
    public static final lp4 w5 = new lp4("LZWDecode");
    public static final lp4 x5 = new lp4("M");
    public static final lp4 y5 = new lp4("Material");
    public static final lp4 z5 = new lp4("Matrix");
    public static final lp4 A5 = new lp4("MacExpertEncoding");
    public static final lp4 B5 = new lp4("MacRomanEncoding");
    public static final lp4 C5 = new lp4("Marked");
    public static final lp4 D5 = new lp4("MarkInfo");
    public static final lp4 E5 = new lp4("Mask");
    public static final lp4 F5 = new lp4("max");
    public static final lp4 G5 = new lp4("Max");
    public static final lp4 H5 = new lp4("MaxLen");
    public static final lp4 I5 = new lp4("MediaBox");
    public static final lp4 J5 = new lp4("MCID");
    public static final lp4 K5 = new lp4("MCR");
    public static final lp4 L5 = new lp4("Metadata");
    public static final lp4 M5 = new lp4("min");
    public static final lp4 N5 = new lp4("Min");
    public static final lp4 O5 = new lp4("MK");
    public static final lp4 P5 = new lp4("MMType1");
    public static final lp4 Q5 = new lp4("ModDate");
    public static final lp4 R5 = new lp4("N");
    public static final lp4 S5 = new lp4("n0");
    public static final lp4 T5 = new lp4("n1");
    public static final lp4 U5 = new lp4("n2");
    public static final lp4 V5 = new lp4("n3");
    public static final lp4 W5 = new lp4("n4");
    public static final lp4 X5 = new lp4("Name");
    public static final lp4 Y5 = new lp4("Named");
    public static final lp4 Z5 = new lp4("Names");
    public static final lp4 a6 = new lp4("Navigation");
    public static final lp4 b6 = new lp4("NavigationPane");
    public static final lp4 c6 = new lp4("Near");
    public static final lp4 d6 = new lp4("NeedAppearances");
    public static final lp4 e6 = new lp4("NewWindow");
    public static final lp4 f6 = new lp4("Next");
    public static final lp4 g6 = new lp4("NextPage");
    public static final lp4 h6 = new lp4("NM");
    public static final lp4 i6 = new lp4("None");
    public static final lp4 j6 = new lp4("NonFullScreenPageMode");
    public static final lp4 k6 = new lp4("NonStruct");
    public static final lp4 l6 = new lp4("Not");
    public static final lp4 m6 = new lp4("Note");
    public static final lp4 n6 = new lp4("NumCopies");
    public static final lp4 o6 = new lp4("Nums");
    public static final lp4 p6 = new lp4("O");
    public static final lp4 q6 = new lp4("Obj");
    public static final lp4 r6 = new lp4("OBJR");
    public static final lp4 s6 = new lp4("ObjStm");
    public static final lp4 t6 = new lp4("OC");
    public static final lp4 u6 = new lp4("OCG");
    public static final lp4 v6 = new lp4("OCGs");
    public static final lp4 w6 = new lp4("OCMD");
    public static final lp4 x6 = new lp4("OCProperties");
    public static final lp4 y6 = new lp4("Off");
    public static final lp4 z6 = new lp4("OFF");
    public static final lp4 A6 = new lp4("ON");
    public static final lp4 B6 = new lp4("OneColumn");
    public static final lp4 C6 = new lp4("Open");
    public static final lp4 D6 = new lp4("OpenAction");
    public static final lp4 E6 = new lp4("OP");
    public static final lp4 F6 = new lp4("op");
    public static final lp4 G6 = new lp4("OPM");
    public static final lp4 H6 = new lp4("Opt");
    public static final lp4 I6 = new lp4("Or");
    public static final lp4 J6 = new lp4("Order");
    public static final lp4 K6 = new lp4("Ordering");
    public static final lp4 L6 = new lp4("Org");
    public static final lp4 M6 = new lp4("Oscillating");
    public static final lp4 N6 = new lp4("Outlines");
    public static final lp4 O6 = new lp4("OutputCondition");
    public static final lp4 P6 = new lp4("OutputConditionIdentifier");
    public static final lp4 Q6 = new lp4("OutputIntent");
    public static final lp4 R6 = new lp4("OutputIntents");
    public static final lp4 S6 = new lp4("P");
    public static final lp4 T6 = new lp4("Page");
    public static final lp4 U6 = new lp4("PageElement");
    public static final lp4 V6 = new lp4("PageLabels");
    public static final lp4 W6 = new lp4("PageLayout");
    public static final lp4 X6 = new lp4("PageMode");
    public static final lp4 Y6 = new lp4("Pages");
    public static final lp4 Z6 = new lp4("PaintType");
    public static final lp4 a7 = new lp4("Panose");
    public static final lp4 b7 = new lp4("Params");
    public static final lp4 c7 = new lp4("Parent");
    public static final lp4 d7 = new lp4("ParentTree");
    public static final lp4 e7 = new lp4("ParentTreeNextKey");
    public static final lp4 f7 = new lp4("Part");
    public static final lp4 g7 = new lp4("PassContextClick");
    public static final lp4 h7 = new lp4("Pattern");
    public static final lp4 i7 = new lp4("PatternType");
    public static final lp4 j7 = new lp4("PC");
    public static final lp4 k7 = new lp4("PDF");
    public static final lp4 l7 = new lp4("PDFDocEncoding");
    public static final lp4 m7 = new lp4("Perceptual");
    public static final lp4 n7 = new lp4("Perms");
    public static final lp4 o7 = new lp4("Pg");
    public static final lp4 p7 = new lp4("PI");
    public static final lp4 q7 = new lp4("PickTrayByPDFSize");
    public static final lp4 r7 = new lp4("PlayCount");
    public static final lp4 s7 = new lp4("PO");
    public static final lp4 t7 = new lp4("Polygon");
    public static final lp4 u7 = new lp4("Polyline");
    public static final lp4 v7 = new lp4("Popup");
    public static final lp4 w7 = new lp4("Position");
    public static final lp4 x7 = new lp4("Predictor");
    public static final lp4 y7 = new lp4("Preferred");
    public static final lp4 z7 = new lp4("Presentation");
    public static final lp4 A7 = new lp4("PreserveRB");
    public static final lp4 B7 = new lp4("Prev");
    public static final lp4 C7 = new lp4("PrevPage");
    public static final lp4 D7 = new lp4("Print");
    public static final lp4 E7 = new lp4("PrintArea");
    public static final lp4 F7 = new lp4("PrintClip");
    public static final lp4 G7 = new lp4("PrintPageRange");
    public static final lp4 H7 = new lp4("PrintScaling");
    public static final lp4 I7 = new lp4("PrintState");
    public static final lp4 J7 = new lp4("Private");
    public static final lp4 K7 = new lp4("ProcSet");
    public static final lp4 L7 = new lp4("Producer");
    public static final lp4 M7 = new lp4("Properties");
    public static final lp4 N7 = new lp4("PS");
    public static final lp4 O7 = new lp4("Adobe.PubSec");
    public static final lp4 P7 = new lp4("PV");
    public static final lp4 Q7 = new lp4("Q");
    public static final lp4 R7 = new lp4("QuadPoints");
    public static final lp4 S7 = new lp4("Quote");
    public static final lp4 T7 = new lp4("R");
    public static final lp4 U7 = new lp4("R2L");
    public static final lp4 V7 = new lp4("Range");
    public static final lp4 W7 = new lp4("RC");
    public static final lp4 X7 = new lp4("RBGroups");
    public static final lp4 Y7 = new lp4("Reason");
    public static final lp4 Z7 = new lp4("Recipients");
    public static final lp4 a8 = new lp4("Rect");
    public static final lp4 b8 = new lp4("Reference");
    public static final lp4 c8 = new lp4("Registry");
    public static final lp4 d8 = new lp4("RegistryName");
    public static final lp4 e8 = new lp4("RelativeColorimetric");
    public static final lp4 f8 = new lp4("Rendition");
    public static final lp4 g8 = new lp4("ResetForm");
    public static final lp4 h8 = new lp4("Resources");
    public static final lp4 i8 = new lp4("RI");
    public static final lp4 j8 = new lp4("RichMedia");
    public static final lp4 k8 = new lp4("RichMediaActivation");
    public static final lp4 l8 = new lp4("RichMediaAnimation");
    public static final lp4 m8 = new lp4("RichMediaCommand");
    public static final lp4 n8 = new lp4("RichMediaConfiguration");
    public static final lp4 o8 = new lp4("RichMediaContent");
    public static final lp4 p8 = new lp4("RichMediaDeactivation");
    public static final lp4 q8 = new lp4("RichMediaExecute");
    public static final lp4 r8 = new lp4("RichMediaInstance");
    public static final lp4 s8 = new lp4("RichMediaParams");
    public static final lp4 t8 = new lp4("RichMediaPosition");
    public static final lp4 u8 = new lp4("RichMediaPresentation");
    public static final lp4 v8 = new lp4("RichMediaSettings");
    public static final lp4 w8 = new lp4("RichMediaWindow");
    public static final lp4 x8 = new lp4("RoleMap");
    public static final lp4 y8 = new lp4("Root");
    public static final lp4 z8 = new lp4("Rotate");
    public static final lp4 A8 = new lp4("Rows");
    public static final lp4 B8 = new lp4("Ruby");
    public static final lp4 C8 = new lp4("RunLengthDecode");
    public static final lp4 D8 = new lp4("RV");
    public static final lp4 E8 = new lp4("S");
    public static final lp4 F8 = new lp4("Saturation");
    public static final lp4 G8 = new lp4("Schema");
    public static final lp4 H8 = new lp4("Screen");
    public static final lp4 I8 = new lp4("Scripts");
    public static final lp4 J8 = new lp4("Sect");
    public static final lp4 K8 = new lp4("Separation");
    public static final lp4 L8 = new lp4("SetOCGState");
    public static final lp4 M8 = new lp4("Settings");
    public static final lp4 N8 = new lp4("Shading");
    public static final lp4 O8 = new lp4("ShadingType");
    public static final lp4 P8 = new lp4("Shift-JIS");
    public static final lp4 Q8 = new lp4("Sig");
    public static final lp4 R8 = new lp4("SigFlags");
    public static final lp4 S8 = new lp4("SigRef");
    public static final lp4 T8 = new lp4("Simplex");
    public static final lp4 U8 = new lp4("SinglePage");
    public static final lp4 V8 = new lp4("Size");
    public static final lp4 W8 = new lp4("SMask");
    public static final lp4 X8 = new lp4("Sort");
    public static final lp4 Y8 = new lp4("Sound");
    public static final lp4 Z8 = new lp4("Span");
    public static final lp4 a9 = new lp4("Speed");
    public static final lp4 b9 = new lp4("Split");
    public static final lp4 c9 = new lp4("Square");
    public static final lp4 d9 = new lp4("Squiggly");
    public static final lp4 e9 = new lp4("St");
    public static final lp4 f9 = new lp4("Stamp");
    public static final lp4 g9 = new lp4("Standard");
    public static final lp4 h9 = new lp4("State");
    public static final lp4 i9 = new lp4("StdCF");
    public static final lp4 j9 = new lp4("StemV");
    public static final lp4 k9 = new lp4("StmF");
    public static final lp4 l9 = new lp4("StrF");
    public static final lp4 m9 = new lp4("StrikeOut");
    public static final lp4 n9 = new lp4("StructElem");
    public static final lp4 o9 = new lp4("StructParent");
    public static final lp4 p9 = new lp4("StructParents");
    public static final lp4 q9 = new lp4("StructTreeRoot");
    public static final lp4 r9 = new lp4("Style");
    public static final lp4 s9 = new lp4("SubFilter");
    public static final lp4 t9 = new lp4("Subject");
    public static final lp4 u9 = new lp4("SubmitForm");
    public static final lp4 v9 = new lp4("Subtype");
    public static final lp4 w9 = new lp4("Supplement");
    public static final lp4 x9 = new lp4("SV");
    public static final lp4 y9 = new lp4("SW");
    public static final lp4 z9 = new lp4("Symbol");
    public static final lp4 A9 = new lp4("T");
    public static final lp4 B9 = new lp4("TA");
    public static final lp4 C9 = new lp4("Table");
    public static final lp4 D9 = new lp4("Tabs");
    public static final lp4 E9 = new lp4("TBody");
    public static final lp4 F9 = new lp4("TD");
    public static final lp4 G9 = new lp4("Text");
    public static final lp4 H9 = new lp4("TFoot");
    public static final lp4 I9 = new lp4("TH");
    public static final lp4 J9 = new lp4("THead");
    public static final lp4 K9 = new lp4("Thumb");
    public static final lp4 L9 = new lp4("Threads");
    public static final lp4 M9 = new lp4("TI");
    public static final lp4 N9 = new lp4("Time");
    public static final lp4 O9 = new lp4("TilingType");
    public static final lp4 P9 = new lp4("Times-Roman");
    public static final lp4 Q9 = new lp4("Times-Bold");
    public static final lp4 R9 = new lp4("Times-Italic");
    public static final lp4 S9 = new lp4("Times-BoldItalic");
    public static final lp4 T9 = new lp4("Title");
    public static final lp4 U9 = new lp4("TK");
    public static final lp4 V9 = new lp4("TM");
    public static final lp4 W9 = new lp4("TOC");
    public static final lp4 X9 = new lp4("TOCI");
    public static final lp4 Y9 = new lp4("Toggle");
    public static final lp4 Z9 = new lp4("Toolbar");
    public static final lp4 aa = new lp4("ToUnicode");
    public static final lp4 ba = new lp4("TP");
    public static final lp4 ca = new lp4("TR");
    public static final lp4 da = new lp4("Trans");
    public static final lp4 ea = new lp4("TransformParams");
    public static final lp4 fa = new lp4("TransformMethod");
    public static final lp4 ga = new lp4("Transparency");
    public static final lp4 ha = new lp4("Transparent");
    public static final lp4 ia = new lp4("Trapped");
    public static final lp4 ja = new lp4("TrimBox");
    public static final lp4 ka = new lp4("TrueType");
    public static final lp4 la = new lp4("Ttl");
    public static final lp4 ma = new lp4("TU");
    public static final lp4 na = new lp4("TwoColumnLeft");
    public static final lp4 oa = new lp4("TwoColumnRight");
    public static final lp4 pa = new lp4("TwoPageLeft");
    public static final lp4 qa = new lp4("TwoPageRight");
    public static final lp4 ra = new lp4("Tx");
    public static final lp4 sa = new lp4("Type");
    public static final lp4 ta = new lp4("Type0");
    public static final lp4 ua = new lp4("Type1");
    public static final lp4 va = new lp4("Type3");
    public static final lp4 wa = new lp4("U");
    public static final lp4 xa = new lp4("UF");
    public static final lp4 ya = new lp4("UHC");
    public static final lp4 za = new lp4("Underline");
    public static final lp4 Aa = new lp4("UR");
    public static final lp4 Ba = new lp4("UR3");
    public static final lp4 Ca = new lp4("URI");
    public static final lp4 Da = new lp4("URL");
    public static final lp4 Ea = new lp4("Usage");
    public static final lp4 Fa = new lp4("UseAttachments");
    public static final lp4 Ga = new lp4("UseNone");
    public static final lp4 Ha = new lp4("UseOC");
    public static final lp4 Ia = new lp4("UseOutlines");
    public static final lp4 Ja = new lp4("User");
    public static final lp4 Ka = new lp4("UserProperties");
    public static final lp4 La = new lp4("UserUnit");
    public static final lp4 Ma = new lp4("UseThumbs");
    public static final lp4 Na = new lp4("V");
    public static final lp4 Oa = new lp4("V2");
    public static final lp4 Pa = new lp4("VAlign");
    public static final lp4 Qa = new lp4("VE");
    public static final lp4 Ra = new lp4("VeriSign.PPKVS");
    public static final lp4 Sa = new lp4("Version");
    public static final lp4 Ta = new lp4("Vertices");
    public static final lp4 Ua = new lp4("Video");
    public static final lp4 Va = new lp4("View");
    public static final lp4 Wa = new lp4("Views");
    public static final lp4 Xa = new lp4("ViewArea");
    public static final lp4 Ya = new lp4("ViewClip");
    public static final lp4 Za = new lp4("ViewerPreferences");
    public static final lp4 ab = new lp4("ViewState");
    public static final lp4 bb = new lp4("VisiblePages");
    public static final lp4 cb = new lp4("VOffset");
    public static final lp4 db = new lp4("W");
    public static final lp4 eb = new lp4("W2");
    public static final lp4 fb = new lp4("Warichu");
    public static final lp4 gb = new lp4("WC");
    public static final lp4 hb = new lp4("Widget");
    public static final lp4 ib = new lp4("Width");
    public static final lp4 jb = new lp4("Widths");
    public static final lp4 kb = new lp4("Win");
    public static final lp4 lb = new lp4("WinAnsiEncoding");
    public static final lp4 mb = new lp4("Window");
    public static final lp4 nb = new lp4("Windowed");
    public static final lp4 ob = new lp4("Wipe");
    public static final lp4 pb = new lp4("WhitePoint");
    public static final lp4 qb = new lp4("WP");
    public static final lp4 rb = new lp4("WS");
    public static final lp4 sb = new lp4("X");
    public static final lp4 tb = new lp4("XA");
    public static final lp4 ub = new lp4("XD");
    public static final lp4 vb = new lp4("XFA");
    public static final lp4 wb = new lp4("XML");
    public static final lp4 xb = new lp4("XObject");
    public static final lp4 yb = new lp4("XStep");
    public static final lp4 zb = new lp4("XRef");
    public static final lp4 Ab = new lp4("XRefStm");
    public static final lp4 Bb = new lp4("XYZ");
    public static final lp4 Cb = new lp4("YStep");
    public static final lp4 Db = new lp4("ZaDb");
    public static final lp4 Eb = new lp4("ZapfDingbats");
    public static final lp4 Fb = new lp4("Zoom");

    static {
        Field[] declaredFields = lp4.class.getDeclaredFields();
        Gb = new HashMap(declaredFields.length);
        for (Field field : declaredFields) {
            try {
                if ((field.getModifiers() & 25) == 25 && field.getType().equals(lp4.class)) {
                    lp4 lp4Var = (lp4) field.get(null);
                    Gb.put(n(lp4Var.toString()), lp4Var);
                }
            } catch (Exception e) {
                e.printStackTrace();
                return;
            }
        }
    }

    public lp4(String str) {
        this(str, true);
    }

    public static String n(String str) {
        StringBuffer stringBuffer = new StringBuffer();
        try {
            int length = str.length();
            int i10 = 1;
            while (i10 < length) {
                char cCharAt = str.charAt(i10);
                if (cCharAt == '#') {
                    char cCharAt2 = str.charAt(i10 + 1);
                    i10 += 2;
                    cCharAt = (char) ((lk4.a(cCharAt2) << 4) + lk4.a(str.charAt(i10)));
                }
                stringBuffer.append(cCharAt);
                i10++;
            }
        } catch (IndexOutOfBoundsException unused) {
        }
        return stringBuffer.toString();
    }

    public static byte[] o(String str) {
        int length = str.length();
        o80 o80Var = new o80(length + 20);
        o80Var.e('/');
        char[] charArray = str.toCharArray();
        for (int i10 = 0; i10 < length; i10++) {
            char c = (char) (charArray[i10] & 255);
            if (c == ' ' || c == '#' || c == '%' || c == '/' || c == '<' || c == '>' || c == '[' || c == ']' || c == '{' || c == '}' || c == '(' || c == ')') {
                o80Var.e('#');
                o80Var.B(Integer.toString(c, 16));
            } else if (c < ' ' || c > '~') {
                o80Var.e('#');
                if (c < 16) {
                    o80Var.e('0');
                }
                o80Var.B(Integer.toString(c, 16));
            } else {
                o80Var.e(c);
            }
        }
        return o80Var.y0();
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        return (obj instanceof lp4) && compareTo((lp4) obj) == 0;
    }

    public int hashCode() {
        int i10 = this.f;
        if (i10 == 0) {
            int length = this.c.length;
            int i11 = 0;
            int i12 = 0;
            while (i11 < length) {
                i10 = (i10 * 31) + (this.c[i12] & UByte.MAX_VALUE);
                i11++;
                i12++;
            }
            this.f = i10;
        }
        return i10;
    }

    @Override // java.lang.Comparable
    /* JADX INFO: renamed from: m, reason: merged with bridge method [inline-methods] */
    public int compareTo(lp4 lp4Var) {
        byte[] bArr = this.c;
        byte[] bArr2 = lp4Var.c;
        int iMin = Math.min(bArr.length, bArr2.length);
        for (int i10 = 0; i10 < iMin; i10++) {
            byte b = bArr[i10];
            byte b10 = bArr2[i10];
            if (b > b10) {
                return 1;
            }
            if (b < b10) {
                return -1;
            }
        }
        if (bArr.length < bArr2.length) {
            return -1;
        }
        return bArr.length > bArr2.length ? 1 : 0;
    }

    public lp4(String str, boolean z10) {
        super(4);
        this.f = 0;
        int length = str.length();
        if (z10 && length > 127) {
            throw new IllegalArgumentException(dt3.b("the.name.1.is.too.long.2.characters", str, String.valueOf(length)));
        }
        this.c = o(str);
    }
}
