package com.zepto;

import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatButton;
import androidx.cardview.widget.CardView;

/* JADX INFO: loaded from: classes2.dex */
public abstract class m7 extends lq7 {
    public final AppCompatButton A;
    public final AppCompatButton B;
    public final ImageView C;
    public final ScrollView D;
    public final EditText E;
    public final EditText F;
    public final EditText G;
    public final LinearLayout H;
    public final LinearLayout I;
    public final vy3 J;
    public final CardView K;
    public final Spinner L;
    public final Spinner M;
    public final Spinner N;
    public final Spinner O;
    public final Spinner P;
    public final TextView Q;
    public final TextView R;
    public final TextView S;
    public final TextView T;
    public final TextView U;
    public final TextView V;
    public final TextView W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;
    public final TextView a0;
    public final TextView b0;
    public final TextView c0;
    public final TextView d0;
    public final TextView e0;
    public final TextView f0;
    public final TextView g0;
    public final TextView h0;
    public final TextView i0;
    public final TextView j0;
    public final TextView k0;
    public final TextView l0;
    public final TextView m0;
    public final TextView n0;
    public final EditText o0;
    public final TextView p0;
    public final TextView q0;
    public final EditText r0;
    public final ImageView w;
    public final ImageView x;
    public final ImageView y;
    public final ImageView z;

    public m7(Object obj, View view, int i, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, AppCompatButton appCompatButton, AppCompatButton appCompatButton2, ImageView imageView5, ScrollView scrollView, EditText editText, EditText editText2, EditText editText3, LinearLayout linearLayout, LinearLayout linearLayout2, vy3 vy3Var, CardView cardView, Spinner spinner, Spinner spinner2, Spinner spinner3, Spinner spinner4, Spinner spinner5, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, TextView textView16, TextView textView17, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, TextView textView23, TextView textView24, EditText editText4, TextView textView25, TextView textView26, EditText editText5) {
        super(obj, view, i);
        this.w = imageView;
        this.x = imageView2;
        this.y = imageView3;
        this.z = imageView4;
        this.A = appCompatButton;
        this.B = appCompatButton2;
        this.C = imageView5;
        this.D = scrollView;
        this.E = editText;
        this.F = editText2;
        this.G = editText3;
        this.H = linearLayout;
        this.I = linearLayout2;
        this.J = vy3Var;
        this.K = cardView;
        this.L = spinner;
        this.M = spinner2;
        this.N = spinner3;
        this.O = spinner4;
        this.P = spinner5;
        this.Q = textView;
        this.R = textView2;
        this.S = textView3;
        this.T = textView4;
        this.U = textView5;
        this.V = textView6;
        this.W = textView7;
        this.X = textView8;
        this.Y = textView9;
        this.Z = textView10;
        this.a0 = textView11;
        this.b0 = textView12;
        this.c0 = textView13;
        this.d0 = textView14;
        this.e0 = textView15;
        this.f0 = textView16;
        this.g0 = textView17;
        this.h0 = textView18;
        this.i0 = textView19;
        this.j0 = textView20;
        this.k0 = textView21;
        this.l0 = textView22;
        this.m0 = textView23;
        this.n0 = textView24;
        this.o0 = editText4;
        this.p0 = textView25;
        this.q0 = textView26;
        this.r0 = editText5;
    }
}
