package com.zepto;

import android.view.LayoutInflater;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatButton;
import com.nic.mparivahan.R;
import com.nic.mparivahan.dlservices.widget.MyTextView;

/* JADX INFO: loaded from: classes2.dex */
public abstract class s8 extends lq7 {
    public final AppCompatButton A;
    public final TextView A0;
    public final TextView B;
    public final TextView B0;
    public final TextView C;
    public final TextView C0;
    public final TextView D;
    public final TextView D0;
    public final TextView E;
    public final TextView E0;
    public final TextView F;
    public final TextView F0;
    public final TextView G;
    public final TextView G0;
    public final TextView H;
    public final TextView H0;
    public final TextView I;
    public final TextView I0;
    public final TextView J;
    public final MyTextView J0;
    public final TextView K;
    public final MyTextView K0;
    public final TextView L;
    public final TextView L0;
    public final TextView M;
    public final TextView M0;
    public final TextView N;
    public final TextView N0;
    public final TextView O;
    public final TextView P;
    public final RadioButton Q;
    public final RadioGroup R;
    public final LinearLayout S;
    public final vy3 T;
    public final RadioButton U;
    public final TextView V;
    public final TextView W;
    public final ImageView X;
    public final ImageView Y;
    public final TextView Z;
    public final TextView a0;
    public final TextView b0;
    public final TextView c0;
    public final TextView d0;
    public final ImageView e0;
    public final ImageView f0;
    public final TextView g0;
    public final TextView h0;
    public final TextView i0;
    public final TextView j0;
    public final TextView k0;
    public final TextView l0;
    public final TextView m0;
    public final TextView n0;
    public final TextView o0;
    public final TextView p0;
    public final TextView q0;
    public final TextView r0;
    public final TextView s0;
    public final TextView t0;
    public final TextView u0;
    public final TextView v0;
    public final LinearLayout w;
    public final TextView w0;
    public final LinearLayout x;
    public final TextView x0;
    public final ImageView y;
    public final TextView y0;
    public final ImageView z;
    public final TextView z0;

    public s8(Object obj, View view, int i, LinearLayout linearLayout, LinearLayout linearLayout2, ImageView imageView, ImageView imageView2, AppCompatButton appCompatButton, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, TextView textView7, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, TextView textView15, RadioButton radioButton, RadioGroup radioGroup, LinearLayout linearLayout3, vy3 vy3Var, RadioButton radioButton2, TextView textView16, TextView textView17, ImageView imageView3, ImageView imageView4, TextView textView18, TextView textView19, TextView textView20, TextView textView21, TextView textView22, ImageView imageView5, ImageView imageView6, TextView textView23, TextView textView24, TextView textView25, TextView textView26, TextView textView27, TextView textView28, TextView textView29, TextView textView30, TextView textView31, TextView textView32, TextView textView33, TextView textView34, TextView textView35, TextView textView36, TextView textView37, TextView textView38, TextView textView39, TextView textView40, TextView textView41, TextView textView42, TextView textView43, TextView textView44, TextView textView45, TextView textView46, TextView textView47, TextView textView48, TextView textView49, TextView textView50, TextView textView51, MyTextView myTextView, MyTextView myTextView2, TextView textView52, TextView textView53, TextView textView54) {
        super(obj, view, i);
        this.w = linearLayout;
        this.x = linearLayout2;
        this.y = imageView;
        this.z = imageView2;
        this.A = appCompatButton;
        this.B = textView;
        this.C = textView2;
        this.D = textView3;
        this.E = textView4;
        this.F = textView5;
        this.G = textView6;
        this.H = textView7;
        this.I = textView8;
        this.J = textView9;
        this.K = textView10;
        this.L = textView11;
        this.M = textView12;
        this.N = textView13;
        this.O = textView14;
        this.P = textView15;
        this.Q = radioButton;
        this.R = radioGroup;
        this.S = linearLayout3;
        this.T = vy3Var;
        this.U = radioButton2;
        this.V = textView16;
        this.W = textView17;
        this.X = imageView3;
        this.Y = imageView4;
        this.Z = textView18;
        this.a0 = textView19;
        this.b0 = textView20;
        this.c0 = textView21;
        this.d0 = textView22;
        this.e0 = imageView5;
        this.f0 = imageView6;
        this.g0 = textView23;
        this.h0 = textView24;
        this.i0 = textView25;
        this.j0 = textView26;
        this.k0 = textView27;
        this.l0 = textView28;
        this.m0 = textView29;
        this.n0 = textView30;
        this.o0 = textView31;
        this.p0 = textView32;
        this.q0 = textView33;
        this.r0 = textView34;
        this.s0 = textView35;
        this.t0 = textView36;
        this.u0 = textView37;
        this.v0 = textView38;
        this.w0 = textView39;
        this.x0 = textView40;
        this.y0 = textView41;
        this.z0 = textView42;
        this.A0 = textView43;
        this.B0 = textView44;
        this.C0 = textView45;
        this.D0 = textView46;
        this.E0 = textView47;
        this.F0 = textView48;
        this.G0 = textView49;
        this.H0 = textView50;
        this.I0 = textView51;
        this.J0 = myTextView;
        this.K0 = myTextView2;
        this.L0 = textView52;
        this.M0 = textView53;
        this.N0 = textView54;
    }

    public static s8 x(LayoutInflater layoutInflater) {
        kd1.d();
        return y(layoutInflater, null);
    }

    public static s8 y(LayoutInflater layoutInflater, Object obj) {
        return (s8) lq7.o(layoutInflater, R.layout.activity_cov_details, null, false, obj);
    }
}
