package com.zepto;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.cardview.widget.CardView;
import com.nic.mparivahan.dlservices.widget.CustomWegetLayout;
import com.nic.mparivahan.dlservices.widget.MyTextView;

/* JADX INFO: loaded from: classes2.dex */
public abstract class xa extends lq7 {
    public final ImageView A;
    public final ImageView A0;
    public final ImageView B;
    public final CustomWegetLayout B0;
    public final TextView C;
    public final TextView D;
    public final TextView E;
    public final TextView F;
    public final TextView G;
    public final TextView H;
    public final vy3 I;
    public final CardView J;
    public final ImageView K;
    public final LinearLayout L;
    public final LinearLayout M;
    public final CardView N;
    public final LinearLayout O;
    public final iy3 P;
    public final LinearLayout Q;
    public final LinearLayout R;
    public final LinearLayout S;
    public final as4 T;
    public final AppCompatTextView U;
    public final CardView V;
    public final TextView W;
    public final MyTextView X;
    public final LinearLayout Y;
    public final LinearLayout Z;
    public final ImageView a0;
    public final CustomWegetLayout b0;
    public final ImageView c0;
    public final ImageView d0;
    public final TextView e0;
    public final TextView f0;
    public final TextView g0;
    public final TextView h0;
    public final TextView i0;
    public final TextView j0;
    public final TextView k0;
    public final AppCompatTextView l0;
    public final TextView m0;
    public final AppCompatTextView n0;
    public final AppCompatTextView o0;
    public final TextView p0;
    public final AppCompatTextView q0;
    public final AppCompatTextView r0;
    public final TextView s0;
    public final AppCompatTextView t0;
    public final AppCompatTextView u0;
    public final TextView v0;
    public final ImageView w;
    public final AppCompatTextView w0;
    public final ImageView x;
    public final TextView x0;
    public final ImageView y;
    public final TextView y0;
    public final ImageView z;
    public final TextView z0;

    public xa(Object obj, View view, int i, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, vy3 vy3Var, CardView cardView, ImageView imageView7, LinearLayout linearLayout, LinearLayout linearLayout2, CardView cardView2, LinearLayout linearLayout3, iy3 iy3Var, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, as4 as4Var, AppCompatTextView appCompatTextView, CardView cardView3, TextView textView7, MyTextView myTextView, LinearLayout linearLayout7, LinearLayout linearLayout8, ImageView imageView8, CustomWegetLayout customWegetLayout, ImageView imageView9, ImageView imageView10, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, AppCompatTextView appCompatTextView2, TextView textView15, AppCompatTextView appCompatTextView3, AppCompatTextView appCompatTextView4, TextView textView16, AppCompatTextView appCompatTextView5, AppCompatTextView appCompatTextView6, TextView textView17, AppCompatTextView appCompatTextView7, AppCompatTextView appCompatTextView8, TextView textView18, AppCompatTextView appCompatTextView9, TextView textView19, TextView textView20, TextView textView21, ImageView imageView11, CustomWegetLayout customWegetLayout2) {
        super(obj, view, i);
        this.w = imageView;
        this.x = imageView2;
        this.y = imageView3;
        this.z = imageView4;
        this.A = imageView5;
        this.B = imageView6;
        this.C = textView;
        this.D = textView2;
        this.E = textView3;
        this.F = textView4;
        this.G = textView5;
        this.H = textView6;
        this.I = vy3Var;
        this.J = cardView;
        this.K = imageView7;
        this.L = linearLayout;
        this.M = linearLayout2;
        this.N = cardView2;
        this.O = linearLayout3;
        this.P = iy3Var;
        this.Q = linearLayout4;
        this.R = linearLayout5;
        this.S = linearLayout6;
        this.T = as4Var;
        this.U = appCompatTextView;
        this.V = cardView3;
        this.W = textView7;
        this.X = myTextView;
        this.Y = linearLayout7;
        this.Z = linearLayout8;
        this.a0 = imageView8;
        this.b0 = customWegetLayout;
        this.c0 = imageView9;
        this.d0 = imageView10;
        this.e0 = textView8;
        this.f0 = textView9;
        this.g0 = textView10;
        this.h0 = textView11;
        this.i0 = textView12;
        this.j0 = textView13;
        this.k0 = textView14;
        this.l0 = appCompatTextView2;
        this.m0 = textView15;
        this.n0 = appCompatTextView3;
        this.o0 = appCompatTextView4;
        this.p0 = textView16;
        this.q0 = appCompatTextView5;
        this.r0 = appCompatTextView6;
        this.s0 = textView17;
        this.t0 = appCompatTextView7;
        this.u0 = appCompatTextView8;
        this.v0 = textView18;
        this.w0 = appCompatTextView9;
        this.x0 = textView19;
        this.y0 = textView20;
        this.z0 = textView21;
        this.A0 = imageView11;
        this.B0 = customWegetLayout2;
    }
}
