package com.zepto;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.cardview.widget.CardView;
import com.nic.mparivahan.dlservices.widget.CustomWegetLayout;

/* JADX INFO: loaded from: classes2.dex */
public abstract class z7 extends lq7 {
    public final ImageView A;
    public final ImageView B;
    public final TextView C;
    public final TextView D;
    public final TextView E;
    public final TextView F;
    public final TextView G;
    public final TextView H;
    public final vy3 I;
    public final LinearLayout J;
    public final LinearLayout K;
    public final CardView L;
    public final LinearLayout M;
    public final iy3 N;
    public final LinearLayout O;
    public final LinearLayout P;
    public final LinearLayout Q;
    public final yn0 R;
    public final AppCompatTextView S;
    public final TextView T;
    public final LinearLayout U;
    public final LinearLayout V;
    public final ImageView W;
    public final CustomWegetLayout X;
    public final ImageView Y;
    public final ImageView Z;
    public final TextView a0;
    public final TextView b0;
    public final TextView c0;
    public final TextView d0;
    public final TextView e0;
    public final TextView f0;
    public final TextView g0;
    public final AppCompatTextView h0;
    public final TextView i0;
    public final AppCompatTextView j0;
    public final AppCompatTextView k0;
    public final TextView l0;
    public final AppCompatTextView m0;
    public final AppCompatTextView n0;
    public final TextView o0;
    public final AppCompatTextView p0;
    public final AppCompatTextView q0;
    public final TextView r0;
    public final AppCompatTextView s0;
    public final TextView t0;
    public final TextView u0;
    public final ImageView v0;
    public final ImageView w;
    public final CustomWegetLayout w0;
    public final ImageView x;
    public final ImageView y;
    public final ImageView z;

    public z7(Object obj, View view, int i, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, TextView textView, TextView textView2, TextView textView3, TextView textView4, TextView textView5, TextView textView6, vy3 vy3Var, LinearLayout linearLayout, LinearLayout linearLayout2, CardView cardView, LinearLayout linearLayout3, iy3 iy3Var, LinearLayout linearLayout4, LinearLayout linearLayout5, LinearLayout linearLayout6, yn0 yn0Var, AppCompatTextView appCompatTextView, TextView textView7, LinearLayout linearLayout7, LinearLayout linearLayout8, ImageView imageView7, CustomWegetLayout customWegetLayout, ImageView imageView8, ImageView imageView9, TextView textView8, TextView textView9, TextView textView10, TextView textView11, TextView textView12, TextView textView13, TextView textView14, AppCompatTextView appCompatTextView2, TextView textView15, AppCompatTextView appCompatTextView3, AppCompatTextView appCompatTextView4, TextView textView16, AppCompatTextView appCompatTextView5, AppCompatTextView appCompatTextView6, TextView textView17, AppCompatTextView appCompatTextView7, AppCompatTextView appCompatTextView8, TextView textView18, AppCompatTextView appCompatTextView9, TextView textView19, TextView textView20, ImageView imageView10, CustomWegetLayout customWegetLayout2) {
        super(obj, view, i);
        this.w = imageView;
        this.x = imageView2;
        this.y = imageView3;
        this.z = imageView4;
        this.A = imageView5;
        this.B = imageView6;
        this.C = textView;
        this.D = textView2;
        this.E = textView3;
        this.F = textView4;
        this.G = textView5;
        this.H = textView6;
        this.I = vy3Var;
        this.J = linearLayout;
        this.K = linearLayout2;
        this.L = cardView;
        this.M = linearLayout3;
        this.N = iy3Var;
        this.O = linearLayout4;
        this.P = linearLayout5;
        this.Q = linearLayout6;
        this.R = yn0Var;
        this.S = appCompatTextView;
        this.T = textView7;
        this.U = linearLayout7;
        this.V = linearLayout8;
        this.W = imageView7;
        this.X = customWegetLayout;
        this.Y = imageView8;
        this.Z = imageView9;
        this.a0 = textView8;
        this.b0 = textView9;
        this.c0 = textView10;
        this.d0 = textView11;
        this.e0 = textView12;
        this.f0 = textView13;
        this.g0 = textView14;
        this.h0 = appCompatTextView2;
        this.i0 = textView15;
        this.j0 = appCompatTextView3;
        this.k0 = appCompatTextView4;
        this.l0 = textView16;
        this.m0 = appCompatTextView5;
        this.n0 = appCompatTextView6;
        this.o0 = textView17;
        this.p0 = appCompatTextView7;
        this.q0 = appCompatTextView8;
        this.r0 = textView18;
        this.s0 = appCompatTextView9;
        this.t0 = textView19;
        this.u0 = textView20;
        this.v0 = imageView10;
        this.w0 = customWegetLayout2;
    }
}
